### ISSUE TITLE
Problem with npm -install

### ISSUE THREAD

**Issue by csakis** [davidjamesstone/vsd#3]
I tried to install vsd globally with npm i -g vsd, I get the same problem as with version 16, the postinstall script fails with this error message:
```
> vsd@0.0.13 create:example C:\Users\csaki\AppData\Roaming\npm\node_modules\vsd
> cd docs && ../bin/vsd.js -c demo

'..' is not recognized as an internal or external command,
operable program or batch file.
```
Then I tried to clone the repo and  ran npm, I get this error now:
```
E:\csaba\Documents\git\vsd>npm i
npm ERR! code ENOLOCAL
npm ERR! Could not install from "..\vsd-plugin-fs" as it does not contain a package.json file.
```

**Comment by davidjamesstone** [comment]
Thanks @csakis - I've published a new version on npm and it seems to be working now. Let me know if you have any further problems.

**Comment by csakis** [comment]
Thanks, David! Global install works now. I installed it successfully both on Mac and Windows
